# Generated by Django 5.2.11 on 2026-07-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itembank", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="itembank.topic",
            ),
        ),
    ]
