# Generated by Django 5.2.11 on 2026-07-12 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_seed_plans"),
        ("itembank", "0002_alter_topic_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal label for this template.", max_length=120
                    ),
                ),
                ("institution_name", models.CharField(max_length=200)),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="E.g. department or faculty name.",
                        max_length=200,
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        blank=True,
                        help_text="Printed in the footer of every page.",
                        max_length=200,
                    ),
                ),
                (
                    "default_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Candidate instructions used when a paper doesn't set its own.",
                    ),
                ),
                (
                    "font",
                    models.CharField(
                        choices=[
                            ("serif", "Serif (Times)"),
                            ("sans", "Sans-serif (Helvetica)"),
                        ],
                        default="serif",
                        max_length=8,
                    ),
                ),
                (
                    "paper_size",
                    models.CharField(
                        choices=[("A4", "A4"), ("LETTER", "US Letter")],
                        default="A4",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("course_code", models.CharField(blank=True, max_length=64)),
                ("exam_date", models.DateField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Overrides the template's default instructions.",
                    ),
                ),
                (
                    "include_answer_space",
                    models.BooleanField(
                        default=True,
                        help_text="Print ruled answer space after essay questions.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="papers",
                        to="formatting.papertemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("instructions", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="formatting.paper",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PaperQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "marks_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Marks for this paper only; blank uses the item's marks.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_usages",
                        to="itembank.item",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="formatting.section",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("section", "item"), name="unique_item_per_section"
                    )
                ],
            },
        ),
    ]
