# Generated by Django 5.2.11 on 2026-07-12 05:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_plans"),
        ("formatting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="papertemplate",
            name="answer_base_mm",
            field=models.DecimalField(decimal_places=1, default=15, max_digits=4),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="answer_per_mark_mm",
            field=models.DecimalField(decimal_places=1, default=18, max_digits=4),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="font_size_pt",
            field=models.DecimalField(decimal_places=1, default=11, max_digits=4),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="line_spacing",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("1.35"), max_digits=4
            ),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="margin_bottom_mm",
            field=models.DecimalField(decimal_places=1, default=20, max_digits=4),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="margin_left_mm",
            field=models.DecimalField(decimal_places=1, default=20, max_digits=4),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="margin_right_mm",
            field=models.DecimalField(decimal_places=1, default=20, max_digits=4),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="margin_top_mm",
            field=models.DecimalField(decimal_places=1, default=18, max_digits=4),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="para_spacing_pt",
            field=models.DecimalField(decimal_places=1, default=6, max_digits=4),
        ),
        migrations.CreateModel(
            name="TemplateDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                ("rendered_pdf", models.BinaryField()),
                ("spec", models.JSONField(default=dict)),
                ("confidence", models.JSONField(default=dict)),
                ("notes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
