# Generated by Django 5.2.11 on 2026-07-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formatting", "0002_papertemplate_answer_base_mm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="papertemplate",
            name="address_text",
            field=models.TextField(
                blank=True, help_text="Shown in the top-right corner of the first page."
            ),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="candidate_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Fill-in lines printed on the cover, e.g. Name, Date, Class.",
            ),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="cover_heading",
            field=models.CharField(
                blank=True,
                help_text="Large centered heading on the first page, e.g. “EXAM”.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="option_label_style",
            field=models.CharField(default="A.", max_length=8),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="question_indent_mm",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="show_header_rule",
            field=models.BooleanField(default=True),
        ),
    ]
