# Generated by Django 5.2.11 on 2026-07-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formatting", "0003_papertemplate_address_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templatedraft",
            name="confidence",
        ),
        migrations.RemoveField(
            model_name="templatedraft",
            name="spec",
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="source_detection",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="source_file",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="source_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="papertemplate",
            name="source_kind",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="templatedraft",
            name="detection",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="templatedraft",
            name="source_file",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="templatedraft",
            name="source_kind",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AlterField(
            model_name="templatedraft",
            name="rendered_pdf",
            field=models.BinaryField(blank=True, default=b""),
        ),
    ]
